### ISSUE TITLE
Change the Entity type to support number as id

### ISSUE THREAD

**Issue by RobinVanCauter** [geckosio/snapshot-interpolation#15]
**Describe the bug**
Inside the following example for compression: https://github.com/geckosio/snapshot-interpolation#compression
You use a number for the id field on your Entity, but the Entity type expects a string as id.

Maybe we can make the type to support both number and string as id?

**Comment by yandeu** [comment]
You can define yourself what type the id can be.
- In `playerSchema`, id is defined as an `uint8`.
- In `snapshotSchema`, id is defined as a `string8` with a length of `6`.
