### ISSUE TITLE
Question about use with physics engine

### ISSUE THREAD

**Issue by zoink** [geckosio/snapshot-interpolation#2]
Thanks for creating this library - the example is a really strong starting point. I’m just curious, would it be possible to make an example demonstrating how a physics engine (specifically enable3d in headless mode on node) could be integrated? Or a rough outline for the steps needed / places to modify the server and client. Thanks so much!

**Comment by yandeu** [comment]
> Thanks for creating this library

You're welcome :)

Have you already looked at these examples:
- https://enable3d.io/examples/headless-mode.html
- https://github.com/geckosio/snapshot-interpolation/tree/master/example
- https://github.com/geckosio/simple-chat-app-example
