### ISSUE TITLE
Bug with calcInterpolation regex

### ISSUE THREAD

**Issue by cfortuner** [geckosio/snapshot-interpolation#3]
Hey! Not urgent, but I found this bug today:

![Screen Shot 2020-07-04 at 2 55 05 PM](https://user-images.githubusercontent.com/5430709/86521508-965d4e80-be06-11ea-99a8-6a148471d244.png)

Given the following schema: 
```
{
   r: number
}
```

and these params: 

calcInterpolation('rad(r)')

the matcher found 2 results and added an extra 'd' to the snapshot. I'm not sure if the 'r' value was updated.

**Comment by yandeu** [comment]
It's `r(rad)` not `rad(r)` :smiley: 

I will quickly update the docs do make it more clear.

**Comment by cfortuner** [comment]
ah! My fault. Thanks yandeu!
