### ISSUE TITLE
State without being an entity

### ISSUE THREAD

**Issue by lucas-jones** [geckosio/snapshot-interpolation#4]
Amazing library. Currently everything in State has to be an `Entity` would be nice if objects could be synced.

Such as to sync:
`{
    gameState: 'ingame' | 'lobby';
    timer: number;
}`

**Comment by yandeu** [comment]
Thanks :smiley: 

But, I'm not exactly sure what you mean.

Can you give me an example of what you're trying to achieve?

**Comment by lucas-jones** [comment]
Sorry bad explanation - was late at night 

```
export type State = Entity[]
export interface Entity {
  id: string
  [key: string]: Value
}
```

So State always has to be `Entity[]` example `{ id: 'heroBlue', x: 23, y: 14, z: 47 },` which has worked great for players. I'm wanting to sync data that isn't entity specific, such as timers, scores, etc.


It would be nice if we could have something like this:

```
export type State = Entity[] | { [key: string]: Value  }

const state: State = {
    players: [
        { id: 'heroBlue', x: 23, y: 14, z: 47 },
        { id: 'heroRed', x: 23, y: 14, z: 47 },
    ],
    timer: {
        timeLeft: 64,
    },
    score: {
        red: 0,
        blue: 2,
    }
}

```

**Comment by lucas-jones** [comment]
Hmmm maybe I'm mistaken. And this shouldn't be part of the `snapshot-interpolation` library. And i just include this data with the packet that includes the snapshot - as score / timer wouldn't need to be interpolated. My misunderstanding

**Comment by yandeu** [comment]
Yes, if it does not have to be interpolated, you do not need to add it inside the snapshot.

You could do this:
```js
const snapshot = SI.snapshot.create({
  players: [
    { id: 0, x: 17.5, y: -1.1 },
    { id: 1, x: 5.8, y: 18.9 }
  ]
})

const data = {
  snapshot: snapshot,
  timer: {
    timeLeft: 64,
  },
  score: {
    red: 0,
    blue: 2,
  }
}

// send data to the client
```
