### ISSUE TITLE
Running without a build

### ISSUE THREAD

**Issue by DolphinIQ** [geckosio/snapshot-interpolation#5]
Hi, I'm in the middle of testing this library. Is it possible to use it without a build step? It works with webpack, but currently my whole projects runs without a need for build, so I can make changes and iterations very quickly. Helps a lot with debugging too :)

The server runs it fine with just `require`, but client doesn't seem compatible with ES6 import. So I'm wondering whether it's possible to bundle it up for the client, like _geckos.io_?

**Comment by yandeu** [comment]
Yes, I can do that. I'm on vacation right now, but I will try to do it as quickly as possible.

**Comment by DolphinIQ** [comment]
Thanks man. Have a great vacation!
I dont mean to hurry you up in any way, please do it whenever you feel like it, but Im just hoping to know if it's a matter of days or weeks or more?

**Comment by yandeu** [comment]
You're welcome. I guess <10 days.

**Comment by yandeu** [comment]
Done.
Checkout the [README](https://github.com/geckosio/snapshot-interpolation#install) file.

**Comment by DolphinIQ** [comment]
Thanks!
