### ISSUE TITLE
Request: Minimal example with phaser and arcade physics

### ISSUE THREAD

**Issue by singerbj** [geckosio/snapshot-interpolation#6]
I think this is the library I've always wanted so I didn't have to try to implement it myself...but I'm struggling to get it to work with Phaser and the Arcade Physics system it offers. I'm not sure how to take what you did in the example in this repo and apply it to an engine with physics. For example, client side prediction would be much more complicated I would think, since thinks like gravity could come into play. Let me know if this is something you think is useful. I have my own repo here where I am trying to get it but haven't gotten it right: https://github.com/singerbj/2d-br

**Comment by yandeu** [comment]
There is a example repo now that includes snapshot interpolation.
https://github.com/geckosio/phaser-on-nodejs-example
