### ISSUE TITLE
Cannot read property "time" of undefined error!

### ISSUE THREAD

**Issue by DolphinIQ** [geckosio/snapshot-interpolation#7]
Hey there! 
I followed your "long version" overview of the SI, really great video btw, presents concepts very well.
The problem comes from the server reconciliation function section. The responsible code line in my app, which triggers the error is:
```js
const playerSnapshot = playerVault.get( serverSnapshot.time, true );
```

When running my game locally, a couple of minutes after start (at random time), the lib crashes with an error: 

![image](https://user-images.githubusercontent.com/34486337/99194794-18c92800-2782-11eb-8ec7-a524b1d76a22.png)

Looking deeper it points to the `Vault.get()` method:

![image](https://user-images.githubusercontent.com/34486337/99194891-c4727800-2782-11eb-9d10-2d3b76649f51.png)

Turns out the problem actually lies in line 23:
```js
var snaps = { older: sorted[i], newer: sorted[i - 1] };
```
I am running into a situation where `if (snap.time <= time) {` is passed as true, when the `for` loop is on it's first iteration. Then the method tries to access the `sorted` array with a negative index of `-1`, returning `undefined`. Since `snaps.newer` is `undefined`, it throws an error when it tries to access `snaps.newer.time`.

To fix this I patched the function with an `if` check after `if (closest) {`:
```js
if (closest) {
  if(snaps.newer == undefined) return;
```
Since I check whether the returned snapshot is `undefined` before continuing, my server reconciliation just `return`s for that particular frame.
I checked with a console log, and Im fine, as it doesn't happen that often - around **3 times per 10 minutes**. I dont know the inner workings of networking so this is very unpredictable to me and may be hard to reproduce the bug.

I dont know the library well, so I am not sure why this happens, or why does it happen so rarely. Should there be such an if check, like I've implemented? What do you think?

**Comment by yandeu** [comment]
> I followed your "long version" overview of the SI, really great video btw, presents concepts very well.

Thanks! I tried my best :D

---

This reproduces the issue:
```ts
const { SnapshotInterpolation } = require('./lib/index')

const SI = new SnapshotInterpolation()

const worldState = [{ id: 1234 }]

const snapshot = SI.snapshot.create(worldState)

SI.vault.add(snapshot)

console.log(snapshot.time)

SI.vault.get(snapshot.time, true)
```
This (https://github.com/geckosio/snapshot-interpolation/commit/ec086158de5ace8e9b27e6c22e620fb25bc86bb6) solves it. What do you think?

**Comment by DolphinIQ** [comment]
> This reproduces the issue:

Oh, that was simpler than I thought :D 

I checked out [ec08615](https://github.com/geckosio/snapshot-interpolation/commit/ec086158de5ace8e9b27e6c22e620fb25bc86bb6). It looks good, but webpack is throwing me an error on the new line 31:
```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|                     const older = Math.abs(time - snaps.older.time);
>                     const newer = Math.abs(time - snaps.newer?.time);
```
Looks like it cant interpret the question mark. Also, we don't need to create `older` and `newer` times to check whether `snaps.newer` is defined, right?
Now that I think about it, it would make sense to check that before the `if (closest) {` line. If the user passed `closest` as `false`, he will get `snaps` object with `older` snapshot and undefined `newer`, which I dont think is the desired result.

**Comment by yandeu** [comment]
The question mark is a [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

Well you can't retrieve a snapshot that you do not have. If there is no newer snapshot, `newer` will be `undefined`.

Maybe in your case it helps increasing the interpolation buffer on the client side:
```ts
const SI = new SnapshotInterpolation()
SI.interpolationBuffer.set(250) // 250ms
```
This will delay the interpolation for 250ms (default is 100). Maybe in the 150ms you have more here, the client will get newer snapshots.

**Comment by ryanhallcs** [comment]
also running into this - until a new version gets published i've been initializing with:

```

        // TODO: remove me once https://github.com/geckosio/snapshot-interpolation/issues/7 is fixed
        Vault.prototype.get = <any> function (time, closest) {
            // zero index is the newest snapshot
            var sorted = this._vault.sort(function (a, b) { return b.time - a.time; });
            if (typeof time === 'undefined')
                return sorted[0];
            for (var i = 0; i < sorted.length; i++) {
                var snap = sorted[i];
                if (snap.time <= time) {
                    var snaps = { older: sorted[i], newer: sorted[i - 1] };
                    if (closest) {
                        var older = Math.abs(time - snaps.older.time);
                        if (!snaps.newer)
                            return snaps.older;
                        var newer = Math.abs(time - snaps.newer.time);
                        if (newer <= older)
                            return snaps.older;
                        else
                            return snaps.newer;
                    }
                    return snaps;
                }
            }
            return;
        };
```

**Comment by yandeu** [comment]
Oh. I kind of lost track of this issue.

It looks like it has been solved here https://github.com/geckosio/snapshot-interpolation/commit/ec086158de5ace8e9b27e6c22e620fb25bc86bb6. I guess I merge it?

**Comment by DolphinIQ** [comment]
It's good, but I'd prefer to use a non optional chaining solution, just to be on the safe side of bundlers and transpilers.

**Comment by yandeu** [comment]
Don't worry about that. The code will automatically be transpiled by the TypeScript compiler.
The final code will look like this:
```js
if (closest) {
    var older = Math.abs(time - snaps.older.time);
    var newer = Math.abs(time - ((_a = snaps.newer) === null || _a === void 0 ? void 0 : _a.time));
    if (isNaN(newer))
        return snaps.older;
    else if (newer <= older)
        return snaps.older;
    else
        return snaps.newer;
}
```
